[package]
name = "obs"
version = "0.1.0"
authors = ["Heliozoa <dm89132@gmail.com>"]
edition = "2018"

[dependencies]
tungstenite = "0.9.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = "2.1"
